### ISSUE TITLE
bundle install - wont work

### ISSUE THREAD

**Issue by dagarin** [hajee/vagrant-centos-5.10-ora12-rac#2]
Hi, I am having a terrible time trying to get this working: 'bundle exec rake install_modules'

I have done the 'gem install bundler' as root but can't get 'bundle install' to work It says I need a Gemfile.  Thing is I have no idea what to put in to the Gemfile if I created one.  Any help would be great.

Thanks
Steve

**Comment by hajee** [comment]
Steve,

I'm sorry to hear that. There are a lot of steps to make a RAC node work. So we have created ruby scripts to do the hard work for you. So you must have a working ruby setup on your system.

The `Gemfile` is in this repo. So after you have cloned this repo to your local disk, you'll have to `cd`  to this directory and then start the work. See [here]*https://github.com/hajee/vagrant-centos-5.10-ora12-rac#the-tools-to-get-it-working) for a short description of the used tools.

**Comment by dagarin** [comment]
Excellent that makes sense.  I am on my way now after cloning the repo.

Thanks
